language: node_js

node_js:
  - 13.2.0

install:
  - npm install

script:
  - npm run coverage
  - npm run build

after_script: 'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  skip_cleanup: true
  on:
    tags: true
